title: Fishpond
email: y.refine@gmail.com
description: personal blog
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tiddler.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings
author: Ruifan Yu # add your name
author-pic: avatar.jpg
about-author: Welcome! My name is Ruifan Yu. I am currenly a Software Engineer in Google, exploring the fabulous ocean of Computer Science.
# Contact links
website: tiddler.github.io # Add your website, do not add http://
linkedin: ruifan-yu # Add your Linkedin handle
github: tiddler # Add your Github handle

# Newsletter
mailchimp: # Add your MailChimp form identifier.

# Disqus
discus_identifier: tiddler # Add your discus identifier

# Tracker
analytics: UA-115676663-1 # Google Analytics

# Paginate
paginate: 6
paginate_path: /page:num/

# Build settings
markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
